version: '3.9'

services:
  api:
    container_name: api-warehouse
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    environment:
      ENV: prod
      SERVER_PORT: 8000
      SERVER_TIMEOUT: 5
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: ejrtrjpidr_idrt
      POSTGRES_PASSWORD: sddeptf
    command:
      - ./app
    depends_on:
      - db

  db:
    container_name: db-postgres
    image: postgres:latest
    restart: always
    ports:
      - 5454:5432
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: ejrtrjpidr_idrt
      POSTGRES_PASSWORD: sddeptf
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
